# Generated by Django 2.0.4 on 2019-04-25 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20180524_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdetail',
            name='comment_info',
            field=models.OneToOneField(blank=True, help_text='基本信息', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detail', to='comment.CommentInfo', verbose_name='基本信息'),
        ),
        migrations.AlterField(
            model_name='commentinfo',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='user.GuestProfile', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='commentinfo',
            name='parent_comment',
            field=models.ForeignKey(blank=True, help_text='根评论', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_comment', to='comment.CommentInfo', verbose_name='根评论'),
        ),
        migrations.AlterField(
            model_name='commentinfo',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='material.PostBaseInfo', verbose_name='所属文章'),
        ),
        migrations.AlterField(
            model_name='commentinfo',
            name='reply_to_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='be_comments', to='user.GuestProfile', verbose_name='被回复人'),
        ),
        migrations.AlterField(
            model_name='commentinfo',
            name='reply_to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply_comment', to='comment.CommentInfo', verbose_name='父级评论'),
        ),
    ]
