# Generated by Django 2.0.4 on 2019-04-25 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180724_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='add_time',
            field=models.DateTimeField(blank=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='book_info',
            field=models.ForeignKey(blank=True, help_text='内容', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='details', to='book.BookInfo', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='update_time',
            field=models.DateTimeField(blank=True, help_text='修改时间', null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='booknotedetail',
            name='add_time',
            field=models.DateTimeField(blank=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='booknotedetail',
            name='book_note_info',
            field=models.ForeignKey(blank=True, help_text='内容', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='details', to='book.BookNoteInfo', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='booknotedetail',
            name='update_time',
            field=models.DateTimeField(blank=True, help_text='修改时间', null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='booknoteinfo',
            name='book',
            field=models.ForeignKey(blank=True, help_text='图书', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='book.BookInfo', verbose_name='图书'),
        ),
        migrations.AlterField(
            model_name='booknoteinfo',
            name='parent_note',
            field=models.ForeignKey(blank=True, help_text='父笔记', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_note', to='book.BookNoteInfo', verbose_name='父笔记'),
        ),
        migrations.AlterField(
            model_name='bookresource',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.BookInfo', verbose_name='图书'),
        ),
    ]
