# Generated by Django 2.0.4 on 2019-04-25 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_auto_20180724_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialbanner',
            name='category',
            field=models.ForeignKey(default='1', help_text='类别', on_delete=django.db.models.deletion.DO_NOTHING, to='material.MaterialCategory', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_category', to='material.MaterialCategory', verbose_name='父类目级别'),
        ),
        migrations.AlterField(
            model_name='materialpicture',
            name='camera',
            field=models.ForeignKey(blank=True, help_text='拍摄相机', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='material.MaterialCamera', verbose_name='拍摄相机'),
        ),
        migrations.AlterField(
            model_name='materialtag',
            name='category',
            field=models.ForeignKey(blank=True, help_text='类别', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='material.MaterialCategory', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='postbaseinfo',
            name='add_time',
            field=models.DateTimeField(blank=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='postbaseinfo',
            name='category',
            field=models.ForeignKey(help_text='类别', on_delete=django.db.models.deletion.DO_NOTHING, to='material.MaterialCategory', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='postbaseinfo',
            name='license',
            field=models.ForeignKey(blank=True, help_text='版权', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='material.MaterialLicense', verbose_name='版权'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='post',
            field=models.ForeignKey(help_text='文章', on_delete=django.db.models.deletion.DO_NOTHING, to='material.PostBaseInfo', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='tag',
            field=models.ForeignKey(help_text='标签', on_delete=django.db.models.deletion.DO_NOTHING, to='material.MaterialTag', verbose_name='标签'),
        ),
    ]
