# Generated by Django 2.0.4 on 2019-04-25 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180629_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggermaster',
            name='blogger',
            field=models.ForeignKey(help_text='个人', on_delete=django.db.models.deletion.DO_NOTHING, to='base.BloggerInfo', verbose_name='个人'),
        ),
        migrations.AlterField(
            model_name='bloggermaster',
            name='master',
            field=models.ForeignKey(help_text='技能', on_delete=django.db.models.deletion.DO_NOTHING, to='material.MaterialMaster', verbose_name='技能'),
        ),
        migrations.AlterField(
            model_name='bloggersocial',
            name='blogger',
            field=models.ForeignKey(help_text='个人', on_delete=django.db.models.deletion.DO_NOTHING, to='base.BloggerInfo', verbose_name='个人'),
        ),
        migrations.AlterField(
            model_name='bloggersocial',
            name='social',
            field=models.ForeignKey(help_text='社交平台', on_delete=django.db.models.deletion.DO_NOTHING, to='material.MaterialSocial', verbose_name='社交平台'),
        ),
        migrations.AlterField(
            model_name='siteinfonavigation',
            name='navigation',
            field=models.ForeignKey(help_text='导航', on_delete=django.db.models.deletion.DO_NOTHING, to='base.NavigationLink', verbose_name='导航'),
        ),
        migrations.AlterField(
            model_name='siteinfonavigation',
            name='site',
            field=models.ForeignKey(help_text='网站', on_delete=django.db.models.deletion.DO_NOTHING, to='base.SiteInfo', verbose_name='网站'),
        ),
    ]
