# Generated by Django 2.0.4 on 2019-04-25 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_moviedetail_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='movie_info',
            field=models.ForeignKey(blank=True, help_text='内容', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='details', to='movie.MovieInfo', verbose_name='内容'),
        ),
    ]
