# Generated by Django 2.0.4 on 2019-04-25 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180617_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='add_time',
            field=models.DateTimeField(blank=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='article_info',
            field=models.ForeignKey(blank=True, help_text='内容', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='details', to='article.ArticleInfo', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='update_time',
            field=models.DateTimeField(blank=True, help_text='修改时间', null=True, verbose_name='修改时间'),
        ),
    ]
