# Generated by Django 2.0.4 on 2019-05-24 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_think', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailythink',
            name='add_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='dailythink',
            name='update_time',
            field=models.DateTimeField(blank=True, help_text='修改时间', null=True, verbose_name='修改时间'),
        ),
    ]
