# Generated by Django 2.0.4 on 2019-05-24 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('age', models.CharField(max_length=25, verbose_name='年代')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('ctage', models.CharField(max_length=25, verbose_name='类别')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('comment', models.TextField(verbose_name='评价')),
            ],
        ),
        migrations.CreateModel(
            name='Poet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_num', models.IntegerField(default=0, help_text='数量', verbose_name='数量')),
                ('age', models.CharField(max_length=25, verbose_name='年代')),
                ('poet_comment', models.TextField(verbose_name='诗人评价')),
                ('name', models.CharField(max_length=25, verbose_name='名字')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('total_url', models.CharField(max_length=255, verbose_name='url')),
                ('poet_inter', models.TextField(verbose_name='诗人介绍')),
            ],
        ),
        migrations.AddField(
            model_name='poem',
            name='auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='poem.Poet'),
        ),
    ]
