# Generated by Django 2.0.4 on 2019-05-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0002_auto_20190524_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='ctage',
            new_name='categ',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='poet',
            name='add_time',
        ),
    ]
