# Generated by Django 2.0.4 on 2019-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0003_auto_20190524_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poet',
            old_name='poet_inter',
            new_name='poet_intr',
        ),
        migrations.AddField(
            model_name='poem',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='poet',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
    ]
