# Generated by Django 2.0.4 on 2019-05-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0005_poet_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='all',
            field=models.IntegerField(blank=True, default=0, help_text='数量', null=True, verbose_name='数量'),
        ),
    ]
