# Generated by Django 2.0.4 on 2019-05-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0006_auto_20190524_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='auth',
            field=models.CharField(max_length=25, verbose_name='作者'),
        ),
    ]
