# Generated by Django 2.0.4 on 2019-05-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0007_auto_20190524_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='auth_name',
            field=models.CharField(default='', max_length=25, verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poem',
            name='auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='poem.Poet'),
        ),
    ]
